language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - DB_DATABASE=onix_codelist_test DB_USERNAME=travis

sudo: false

services:
  - mysql

install:
   - composer update --prefer-dist --no-interaction --prefer-stable

before_script:
  - mysql -e 'create database onix_codelist_test;'
