language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - DB_DATABASE=onix_codelist_test DB_USERNAME=travis

sudo: required

services:
  - mysql

cache:
  - apt

addons:
  apt:
    packages:
      - nginx
      - realpath

install:
  - composer install
  - sudo travis/install-nginx.sh

script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - mysql -e 'create database onix_codelist_test;'
  - curl -vsf 'http://localhost:8080/hello.php' &> /dev/stdout
  - cat /tmp/error.log