language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - DB_DATABASE=onix_codelist_test DB_USERNAME=travis

sudo: false

services:
  - mysql

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - mysql -e 'create database onix_codelist_test;'
